#- name: Install Python
#  raw: sudo pkg install python3

  # Now that we're actually able to, gather facts.
- name: Gathering facts
  setup:

- name: Install common packages
  raw: yes | sudo pkg install {{ item }}
  #    name: "{{ item }}"
  #    state: "present"
  with_items:
    - sudo
    - git
    - fish
    - htop
    - ruby
    - neovim
    - tree
    - xfce4-terminal
    - fluxbox
    - xorg
    - hexchat
    - firefox
